<a href="https://colab.research.google.com/github/rcshivaji/hello-world/blob/master/encoding_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from keras.layers import Embedding
from keras.models import Sequential
import keras as K
import numpy as np

In [0]:
from keras.preprocessing.text import one_hot

In [0]:
docs = ['मोदी-ट्रम्प हैं तो मुमकिन है! देखिये',
        'दिल्ली हिंसा में अबतक 10 लोगों की मौत....देखिए हिंसा पर क्या कहा बीजेपी प्रवक्ता राजनीतिक विश्लेषक ',
        'दिल्ली पुलिस के प्रवक्ता एम एस रंधावा ने कहा- फिलहाल हिंसा पर काबू पा लिया गया है लाइव',
        'भारत के करीब 6.6 करोड़ बच्चे रोज वेब की खाक छानते हैं और ऐसे में वे बढ़ते पोर्नोग्राफी बाजार का शिकार बन जाने के जोखिम ',
        'भारतीय नृत्यकला को अमेरिकी प्रथम महिला मेलानिया ट्रंप के सामने प्रदर्शित करने वाले बच्चों से बातचीत',
        'अमेरिकी राष्ट्रपति  को ताज का दीदार कराने वाले गाइड नितिन सिंह के लिए ये पूरा मौका काफी ख़ास था']

In [12]:
vocab_size = 100

encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[97, 82, 75, 35, 5, 86, 34], [50, 71, 87, 53, 98, 86, 59, 91, 6, 71, 63, 58, 66, 61, 13, 47, 87], [50, 78, 7, 13, 42, 24, 48, 83, 66, 6, 71, 63, 40, 91, 15, 8, 86, 94], [72, 7, 95, 39, 39, 86, 83, 13, 65, 59, 54, 19, 75, 98, 54, 87, 34, 30, 29, 8, 94, 36, 44, 97, 7, 32], [28, 4, 71, 16, 33, 98, 60, 53, 7, 10, 80, 17, 90, 19, 75, 56], [16, 61, 71, 20, 94, 19, 34, 90, 4, 85, 47, 7, 58, 21, 8, 69, 16, 40, 55]]


In [13]:
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM

import numpy as np

embedding_length = 5
max_doc_len = 10

encoded_docs = pad_sequences(encoded_docs, truncating='post', padding='post', maxlen=max_doc_len)

print(encoded_docs)

[[97 82 75 35  5 86 34  0  0  0]
 [50 71 87 53 98 86 59 91  6 71]
 [50 78  7 13 42 24 48 83 66  6]
 [72  7 95 39 39 86 83 13 65 59]
 [28  4 71 16 33 98 60 53  7 10]
 [16 61 71 20 94 19 34 90  4 85]]
